import { mapS3KeyToPublicUrl } from 'src/services/aws'

function lottiePath(name: string, version = 0): string {
  const qs = version ? `?v=${version}` : ''
  return mapS3KeyToPublicUrl(`lottie/${name}.json${qs}`)
}

export const LottieLibrary = {
  clouds_2: lottiePath('clouds_no_bkg'),
  hearts_pluses: lottiePath('hearts_pluses'),
  sunrise_moon: lottiePath('sunrise_moon'),
  rainbow: lottiePath('rainbow_15fps'),
  blob_1: lottiePath('lf30_editor_5Wf0un'),
  grey_circle: lottiePath('lf30_editor_KZiPvZ'),
  blue_yellow_circles: lottiePath('lf30_editor_95jHbq'),
  yellow_warp_glitter: lottiePath('lf30_editor_gC67aw'),
  concentric_circles: lottiePath('lf20_8BYzaH'),
  glitter_bomb: lottiePath('confetti_manoj'),
  sixtysecondtimer1: lottiePath('sixtysecondtimer1'),
  hit_explosion: lottiePath('lf20_ha7mWN'),
  dizzy_stars: lottiePath('lf20_P8rlFD'),
  cogs: lottiePath('lf20_cCiu12'),
  poke: lottiePath('poke', 1),
  lick: lottiePath('lick'),
  tickle: lottiePath('tickle', 1),
  hug: lottiePath('hug', 1),
  bite: lottiePath('bite'),
  kiss: lottiePath('kiss'),
  punch: lottiePath('punch', 1),
  slap: lottiePath('slap', 1),
  scratch: lottiePath('scratch', 1),
  pet: lottiePath('pet', 1),
  buff_crown: lottiePath('buff_crown'),
  heart_particles: lottiePath('heart_particles'),
  loading_particles: lottiePath('loading_particles'),
  pickup: lottiePath('pickup', 1),
  countdown: lottiePath('countdown', 1),
  countdown_overlay_full: lottiePath('countdown_overlay_full'),
  countdown_fullscreen: lottiePath('countdown_fullscreen', 2),
  spinning_rainbow: lottiePath('spinning_rainbow'),
  spinning_star: lottiePath('spinning_star'),
  fireworks: lottiePath('fireworks'),
  spinning_particles: lottiePath('spinning_particles', 1),
  spinning_particles_small: lottiePath('spinning_particles_small', 1),
  confetti: lottiePath('confetti'),
  glitter: lottiePath('glitter'),
  mosquito: lottiePath('mosquito'),
  anvil: lottiePath('anvil'),
  confused_bg: lottiePath('confused_bg'),
  confused_fg: lottiePath('confused_fg'),
  dizzy_bg: lottiePath('dizzy_bg'),
  dizzy_fg: lottiePath('dizzy_fg'),
  spinning_birds: lottiePath('spinning_birds'),
  sunny_mist: lottiePath('sunny_mist'),
  sweet_talk: lottiePath('sweet_talk'),
  buff_pollen: lottiePath('buff_pollen', 1),
  spinning_butterflies: lottiePath('spinning_butterflies'),
  reel_spin: lottiePath('reel_spin', 5),
  water_splash: lottiePath('water_splash_417', 5),
}
