/* NOTE: This file is auto-generated by /bin/airtable/sync-fake-users.ts, don't override manually */

import { Gender } from 'src/gql-types'
import { assets } from 'src/domain/assets'
import { FakeUser } from './types'
export * from './types'

const data = {
  'unreal-fakebeyonce': {
    id: 'unreal-fakebeyonce',
    displayName: 'Beyonce',
    email: 'fakebeyonce@unreal.fun',
    username: 'fakebeyonce',
    gender: Gender.Female,
    password: 'test',
    birthday: new Date('1981-09-04T00:00:00Z'),
    bio: 'I\'m a Rockstar!',
    s3Key: assets.fake_beyonce_934.s3Key,
    signedUpAt: new Date('2020-01-01T00:00:00Z'),
    isVerifiedAccount: false,
    isConfirmed: true,
    hasCompletedSignup: true,
  },
  'unreal-faketrump': {
    id: 'unreal-faketrump',
    displayName: 'Donald Trump',
    email: 'faketrump@unreal.fun',
    username: 'faketrump',
    gender: Gender.Male,
    password: 'test',
    birthday: new Date('1946-06-12T00:00:00Z'),
    bio: 'I\'m a Douche Bag',
    s3Key: assets.fake_trump_932.s3Key,
    signedUpAt: new Date('2020-01-01T00:00:00Z'),
    isVerifiedAccount: false,
    isConfirmed: true,
    hasCompletedSignup: true,
  },
  'unreal-fakebieber': {
    id: 'unreal-fakebieber',
    displayName: 'Justin Bieber',
    email: 'fakebieber@unreal.fun',
    username: 'fakebieber',
    gender: Gender.Male,
    password: 'test',
    birthday: new Date('1994-03-01T00:00:00Z'),
    bio: 'I go my own direction',
    s3Key: assets.fake_justin_933.s3Key,
    signedUpAt: new Date('2020-01-01T00:00:00Z'),
    isVerifiedAccount: false,
    isConfirmed: true,
    hasCompletedSignup: true,
  },
  'unreal-system-user': {
    id: 'unreal-system-user',
    displayName: 'Unreal',
    email: 'systemuser@unreal.fun',
    username: 'unreal',
    gender: Gender.NonBinary,
    password: 'test',
    birthday: new Date('2020-03-01T00:00:00Z'),
    bio: 'Playful Fun',
    s3Key: assets.unreal_robot_935.s3Key,
    signedUpAt: new Date('2020-01-01T00:00:00Z'),
    isVerifiedAccount: true,
    isConfirmed: true,
    hasCompletedSignup: true,
  },
} as const

export const fakeUsers: (Record<keyof typeof data, FakeUser> & typeof data) = data
