version: "3.7"

services:
  redis:
    image: redis:alpine
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
      - redis-data:/usr/local/etc/redis/redis.conf

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 6380:8081

  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=unreal
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  redis-data:
  postgres-data:
