import {MigrationInterface, QueryRunner } from 'typeorm'

export class UserNewsfeedItemEdge1584637052362 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query('CREATE TYPE "user_newsfeed_item_edge_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('CREATE TABLE "user_newsfeed_item_edge" ("id" character varying NOT NULL, "entityType" "user_newsfeed_item_edge_entitytype_enum" NOT NULL DEFAULT \'UserNewsfeedItemEdge\', "userId" character varying NOT NULL, "newsfeedItemId" character varying NOT NULL, "metadata" json, "isDeleted" boolean NOT NULL DEFAULT false, "trackingId" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "recordVersion" integer NOT NULL, CONSTRAINT "PK_09c0594581f3077d1349f75ecae" PRIMARY KEY ("id"))')
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_8ce9fa6de3ccb2f2e1c7faf3b0" ON "user_newsfeed_item_edge" ("userId", "newsfeedItemId") ')
    await queryRunner.query('CREATE INDEX "IDX_ca683d2297753686447c3a1c51" ON "user_newsfeed_item_edge" ("isDeleted", "userId", "createdAt") ')
    await queryRunner.query('ALTER TYPE "public"."edge_entitytype_enum" RENAME TO "edge_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "edge_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "entityType" TYPE "edge_entitytype_enum" USING "entityType"::"text"::"edge_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "entityType" SET DEFAULT \'Edge\'')
    await queryRunner.query('DROP TYPE "edge_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."edge_thisentitytype_enum" RENAME TO "edge_thisentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "edge_thisentitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "thisEntityType" TYPE "edge_thisentitytype_enum" USING "thisEntityType"::"text"::"edge_thisentitytype_enum"')
    await queryRunner.query('DROP TYPE "edge_thisentitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."edge_thatentitytype_enum" RENAME TO "edge_thatentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "edge_thatentitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "thatEntityType" TYPE "edge_thatentitytype_enum" USING "thatEntityType"::"text"::"edge_thatentitytype_enum"')
    await queryRunner.query('DROP TYPE "edge_thatentitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."q_edge_entitytype_enum" RENAME TO "q_edge_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "q_edge_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "q_edge" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "q_edge" ALTER COLUMN "entityType" TYPE "q_edge_entitytype_enum" USING "entityType"::"text"::"q_edge_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "q_edge" ALTER COLUMN "entityType" SET DEFAULT \'QEdge\'')
    await queryRunner.query('DROP TYPE "q_edge_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."q_edge_thisentitytype_enum" RENAME TO "q_edge_thisentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "q_edge_thisentitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "q_edge" ALTER COLUMN "thisEntityType" TYPE "q_edge_thisentitytype_enum" USING "thisEntityType"::"text"::"q_edge_thisentitytype_enum"')
    await queryRunner.query('DROP TYPE "q_edge_thisentitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."q_edge_thatentitytype_enum" RENAME TO "q_edge_thatentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "q_edge_thatentitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "q_edge" ALTER COLUMN "thatEntityType" TYPE "q_edge_thatentitytype_enum" USING "thatEntityType"::"text"::"q_edge_thatentitytype_enum"')
    await queryRunner.query('DROP TYPE "q_edge_thatentitytype_enum_old"')
    await queryRunner.query('DROP INDEX "IDX_3e36162182706a7927adba36fc"')
    await queryRunner.query('ALTER TYPE "public"."s_dist_entitytype_enum" RENAME TO "s_dist_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "s_dist_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "s_dist" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "s_dist" ALTER COLUMN "entityType" TYPE "s_dist_entitytype_enum" USING "entityType"::"text"::"s_dist_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "s_dist" ALTER COLUMN "entityType" SET DEFAULT \'SDist\'')
    await queryRunner.query('DROP TYPE "s_dist_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."s_dist_startingnodeentitytype_enum" RENAME TO "s_dist_startingnodeentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "s_dist_startingnodeentitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "s_dist" ALTER COLUMN "startingNodeEntityType" TYPE "s_dist_startingnodeentitytype_enum" USING "startingNodeEntityType"::"text"::"s_dist_startingnodeentitytype_enum"')
    await queryRunner.query('DROP TYPE "s_dist_startingnodeentitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."s_dist_endingnodeentitytype_enum" RENAME TO "s_dist_endingnodeentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "s_dist_endingnodeentitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "s_dist" ALTER COLUMN "endingNodeEntityType" TYPE "s_dist_endingnodeentitytype_enum" USING "endingNodeEntityType"::"text"::"s_dist_endingnodeentitytype_enum"')
    await queryRunner.query('DROP TYPE "s_dist_endingnodeentitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."effect_entitytype_enum" RENAME TO "effect_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "effect_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "effect" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "effect" ALTER COLUMN "entityType" TYPE "effect_entitytype_enum" USING "entityType"::"text"::"effect_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "effect" ALTER COLUMN "entityType" SET DEFAULT \'Effect\'')
    await queryRunner.query('DROP TYPE "effect_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."effect_thisentitytype_enum" RENAME TO "effect_thisentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "effect_thisentitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "effect" ALTER COLUMN "thisEntityType" TYPE "effect_thisentitytype_enum" USING "thisEntityType"::"text"::"effect_thisentitytype_enum"')
    await queryRunner.query('DROP TYPE "effect_thisentitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."newsfeed_item_entitytype_enum" RENAME TO "newsfeed_item_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "newsfeed_item_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "newsfeed_item" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "newsfeed_item" ALTER COLUMN "entityType" TYPE "newsfeed_item_entitytype_enum" USING "entityType"::"text"::"newsfeed_item_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "newsfeed_item" ALTER COLUMN "entityType" SET DEFAULT \'NewsfeedItem\'')
    await queryRunner.query('DROP TYPE "newsfeed_item_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."comment_entitytype_enum" RENAME TO "comment_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "comment_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "comment" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "comment" ALTER COLUMN "entityType" TYPE "comment_entitytype_enum" USING "entityType"::"text"::"comment_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "comment" ALTER COLUMN "entityType" SET DEFAULT \'Comment\'')
    await queryRunner.query('DROP TYPE "comment_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."comment_receipt_entitytype_enum" RENAME TO "comment_receipt_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "comment_receipt_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "comment_receipt" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "comment_receipt" ALTER COLUMN "entityType" TYPE "comment_receipt_entitytype_enum" USING "entityType"::"text"::"comment_receipt_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "comment_receipt" ALTER COLUMN "entityType" SET DEFAULT \'CommentReceipt\'')
    await queryRunner.query('DROP TYPE "comment_receipt_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."receipt_entitytype_enum" RENAME TO "receipt_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "receipt_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "receipt" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "receipt" ALTER COLUMN "entityType" TYPE "receipt_entitytype_enum" USING "entityType"::"text"::"receipt_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "receipt" ALTER COLUMN "entityType" SET DEFAULT \'Receipt\'')
    await queryRunner.query('DROP TYPE "receipt_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."field_entitytype_enum" RENAME TO "field_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "field_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "field" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "field" ALTER COLUMN "entityType" TYPE "field_entitytype_enum" USING "entityType"::"text"::"field_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "field" ALTER COLUMN "entityType" SET DEFAULT \'Field\'')
    await queryRunner.query('DROP TYPE "field_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."field_thisentitytype_enum" RENAME TO "field_thisentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "field_thisentitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "field" ALTER COLUMN "thisEntityType" TYPE "field_thisentitytype_enum" USING "thisEntityType"::"text"::"field_thisentitytype_enum"')
    await queryRunner.query('DROP TYPE "field_thisentitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."tile_entitytype_enum" RENAME TO "tile_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "tile_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "tile" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "tile" ALTER COLUMN "entityType" TYPE "tile_entitytype_enum" USING "entityType"::"text"::"tile_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "tile" ALTER COLUMN "entityType" SET DEFAULT \'Tile\'')
    await queryRunner.query('DROP TYPE "tile_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."tile_thisentitytype_enum" RENAME TO "tile_thisentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "tile_thisentitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "tile" ALTER COLUMN "thisEntityType" TYPE "tile_thisentitytype_enum" USING "thisEntityType"::"text"::"tile_thisentitytype_enum"')
    await queryRunner.query('DROP TYPE "tile_thisentitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."chat_room_entitytype_enum" RENAME TO "chat_room_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "chat_room_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "chat_room" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "chat_room" ALTER COLUMN "entityType" TYPE "chat_room_entitytype_enum" USING "entityType"::"text"::"chat_room_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "chat_room" ALTER COLUMN "entityType" SET DEFAULT \'ChatRoom\'')
    await queryRunner.query('DROP TYPE "chat_room_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."notification_entitytype_enum" RENAME TO "notification_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "notification_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "notification" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "notification" ALTER COLUMN "entityType" TYPE "notification_entitytype_enum" USING "entityType"::"text"::"notification_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "notification" ALTER COLUMN "entityType" SET DEFAULT \'Notification\'')
    await queryRunner.query('DROP TYPE "notification_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."location_entitytype_enum" RENAME TO "location_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "location_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "location" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "location" ALTER COLUMN "entityType" TYPE "location_entitytype_enum" USING "entityType"::"text"::"location_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "location" ALTER COLUMN "entityType" SET DEFAULT \'Location\'')
    await queryRunner.query('DROP TYPE "location_entitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."job_entitytype_enum" RENAME TO "job_entitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "job_entitytype_enum" AS ENUM(\'Activity\', \'UnObject\', \'User\', \'NewsfeedItem\', \'Edge\', \'Field\', \'Comment\', \'DeviceInfo\', \'ChatRoom\', \'Notification\', \'CommentReceipt\', \'Receipt\', \'Effect\', \'CompletedAction\', \'ActionX\', \'Tile\', \'QEdge\', \'SDist\', \'Report\', \'Location\', \'Job\', \'UserNewsfeedItemEdge\')')
    await queryRunner.query('ALTER TABLE "job" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "job" ALTER COLUMN "entityType" TYPE "job_entitytype_enum" USING "entityType"::"text"::"job_entitytype_enum"')
    await queryRunner.query('ALTER TABLE "job" ALTER COLUMN "entityType" SET DEFAULT \'Job\'')
    await queryRunner.query('DROP TYPE "job_entitytype_enum_old"')
    await queryRunner.query('CREATE INDEX "IDX_3e36162182706a7927adba36fc" ON "s_dist" ("startingNodeEid", "endingNodeEntityType", "buildPhase") ')
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query('DROP INDEX "IDX_3e36162182706a7927adba36fc"')
    await queryRunner.query('CREATE TYPE "job_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "job" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "job" ALTER COLUMN "entityType" TYPE "job_entitytype_enum_old" USING "entityType"::"text"::"job_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "job" ALTER COLUMN "entityType" SET DEFAULT \'Job\'')
    await queryRunner.query('DROP TYPE "job_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "job_entitytype_enum_old" RENAME TO  "job_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "location_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "location" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "location" ALTER COLUMN "entityType" TYPE "location_entitytype_enum_old" USING "entityType"::"text"::"location_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "location" ALTER COLUMN "entityType" SET DEFAULT \'Location\'')
    await queryRunner.query('DROP TYPE "location_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "location_entitytype_enum_old" RENAME TO  "location_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "notification_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "notification" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "notification" ALTER COLUMN "entityType" TYPE "notification_entitytype_enum_old" USING "entityType"::"text"::"notification_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "notification" ALTER COLUMN "entityType" SET DEFAULT \'Notification\'')
    await queryRunner.query('DROP TYPE "notification_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "notification_entitytype_enum_old" RENAME TO  "notification_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "chat_room_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "chat_room" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "chat_room" ALTER COLUMN "entityType" TYPE "chat_room_entitytype_enum_old" USING "entityType"::"text"::"chat_room_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "chat_room" ALTER COLUMN "entityType" SET DEFAULT \'ChatRoom\'')
    await queryRunner.query('DROP TYPE "chat_room_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "chat_room_entitytype_enum_old" RENAME TO  "chat_room_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "tile_thisentitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "tile" ALTER COLUMN "thisEntityType" TYPE "tile_thisentitytype_enum_old" USING "thisEntityType"::"text"::"tile_thisentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "tile_thisentitytype_enum"')
    await queryRunner.query('ALTER TYPE "tile_thisentitytype_enum_old" RENAME TO  "tile_thisentitytype_enum"')
    await queryRunner.query('CREATE TYPE "tile_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "tile" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "tile" ALTER COLUMN "entityType" TYPE "tile_entitytype_enum_old" USING "entityType"::"text"::"tile_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "tile" ALTER COLUMN "entityType" SET DEFAULT \'Tile\'')
    await queryRunner.query('DROP TYPE "tile_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "tile_entitytype_enum_old" RENAME TO  "tile_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "field_thisentitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "field" ALTER COLUMN "thisEntityType" TYPE "field_thisentitytype_enum_old" USING "thisEntityType"::"text"::"field_thisentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "field_thisentitytype_enum"')
    await queryRunner.query('ALTER TYPE "field_thisentitytype_enum_old" RENAME TO  "field_thisentitytype_enum"')
    await queryRunner.query('CREATE TYPE "field_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "field" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "field" ALTER COLUMN "entityType" TYPE "field_entitytype_enum_old" USING "entityType"::"text"::"field_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "field" ALTER COLUMN "entityType" SET DEFAULT \'Field\'')
    await queryRunner.query('DROP TYPE "field_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "field_entitytype_enum_old" RENAME TO  "field_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "receipt_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "receipt" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "receipt" ALTER COLUMN "entityType" TYPE "receipt_entitytype_enum_old" USING "entityType"::"text"::"receipt_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "receipt" ALTER COLUMN "entityType" SET DEFAULT \'Receipt\'')
    await queryRunner.query('DROP TYPE "receipt_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "receipt_entitytype_enum_old" RENAME TO  "receipt_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "comment_receipt_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "comment_receipt" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "comment_receipt" ALTER COLUMN "entityType" TYPE "comment_receipt_entitytype_enum_old" USING "entityType"::"text"::"comment_receipt_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "comment_receipt" ALTER COLUMN "entityType" SET DEFAULT \'CommentReceipt\'')
    await queryRunner.query('DROP TYPE "comment_receipt_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "comment_receipt_entitytype_enum_old" RENAME TO  "comment_receipt_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "comment_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "comment" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "comment" ALTER COLUMN "entityType" TYPE "comment_entitytype_enum_old" USING "entityType"::"text"::"comment_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "comment" ALTER COLUMN "entityType" SET DEFAULT \'Comment\'')
    await queryRunner.query('DROP TYPE "comment_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "comment_entitytype_enum_old" RENAME TO  "comment_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "newsfeed_item_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "newsfeed_item" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "newsfeed_item" ALTER COLUMN "entityType" TYPE "newsfeed_item_entitytype_enum_old" USING "entityType"::"text"::"newsfeed_item_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "newsfeed_item" ALTER COLUMN "entityType" SET DEFAULT \'NewsfeedItem\'')
    await queryRunner.query('DROP TYPE "newsfeed_item_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "newsfeed_item_entitytype_enum_old" RENAME TO  "newsfeed_item_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "effect_thisentitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "effect" ALTER COLUMN "thisEntityType" TYPE "effect_thisentitytype_enum_old" USING "thisEntityType"::"text"::"effect_thisentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "effect_thisentitytype_enum"')
    await queryRunner.query('ALTER TYPE "effect_thisentitytype_enum_old" RENAME TO  "effect_thisentitytype_enum"')
    await queryRunner.query('CREATE TYPE "effect_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "effect" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "effect" ALTER COLUMN "entityType" TYPE "effect_entitytype_enum_old" USING "entityType"::"text"::"effect_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "effect" ALTER COLUMN "entityType" SET DEFAULT \'Effect\'')
    await queryRunner.query('DROP TYPE "effect_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "effect_entitytype_enum_old" RENAME TO  "effect_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "s_dist_endingnodeentitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "s_dist" ALTER COLUMN "endingNodeEntityType" TYPE "s_dist_endingnodeentitytype_enum_old" USING "endingNodeEntityType"::"text"::"s_dist_endingnodeentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "s_dist_endingnodeentitytype_enum"')
    await queryRunner.query('ALTER TYPE "s_dist_endingnodeentitytype_enum_old" RENAME TO  "s_dist_endingnodeentitytype_enum"')
    await queryRunner.query('CREATE TYPE "s_dist_startingnodeentitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "s_dist" ALTER COLUMN "startingNodeEntityType" TYPE "s_dist_startingnodeentitytype_enum_old" USING "startingNodeEntityType"::"text"::"s_dist_startingnodeentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "s_dist_startingnodeentitytype_enum"')
    await queryRunner.query('ALTER TYPE "s_dist_startingnodeentitytype_enum_old" RENAME TO  "s_dist_startingnodeentitytype_enum"')
    await queryRunner.query('CREATE TYPE "s_dist_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "s_dist" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "s_dist" ALTER COLUMN "entityType" TYPE "s_dist_entitytype_enum_old" USING "entityType"::"text"::"s_dist_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "s_dist" ALTER COLUMN "entityType" SET DEFAULT \'SDist\'')
    await queryRunner.query('DROP TYPE "s_dist_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "s_dist_entitytype_enum_old" RENAME TO  "s_dist_entitytype_enum"')
    await queryRunner.query('CREATE INDEX "IDX_3e36162182706a7927adba36fc" ON "s_dist" ("buildPhase", "startingNodeEid", "endingNodeEntityType") ')
    await queryRunner.query('CREATE TYPE "q_edge_thatentitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "q_edge" ALTER COLUMN "thatEntityType" TYPE "q_edge_thatentitytype_enum_old" USING "thatEntityType"::"text"::"q_edge_thatentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "q_edge_thatentitytype_enum"')
    await queryRunner.query('ALTER TYPE "q_edge_thatentitytype_enum_old" RENAME TO  "q_edge_thatentitytype_enum"')
    await queryRunner.query('CREATE TYPE "q_edge_thisentitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "q_edge" ALTER COLUMN "thisEntityType" TYPE "q_edge_thisentitytype_enum_old" USING "thisEntityType"::"text"::"q_edge_thisentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "q_edge_thisentitytype_enum"')
    await queryRunner.query('ALTER TYPE "q_edge_thisentitytype_enum_old" RENAME TO  "q_edge_thisentitytype_enum"')
    await queryRunner.query('CREATE TYPE "q_edge_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "q_edge" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "q_edge" ALTER COLUMN "entityType" TYPE "q_edge_entitytype_enum_old" USING "entityType"::"text"::"q_edge_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "q_edge" ALTER COLUMN "entityType" SET DEFAULT \'QEdge\'')
    await queryRunner.query('DROP TYPE "q_edge_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "q_edge_entitytype_enum_old" RENAME TO  "q_edge_entitytype_enum"')
    await queryRunner.query('CREATE TYPE "edge_thatentitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "thatEntityType" TYPE "edge_thatentitytype_enum_old" USING "thatEntityType"::"text"::"edge_thatentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "edge_thatentitytype_enum"')
    await queryRunner.query('ALTER TYPE "edge_thatentitytype_enum_old" RENAME TO  "edge_thatentitytype_enum"')
    await queryRunner.query('CREATE TYPE "edge_thisentitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "thisEntityType" TYPE "edge_thisentitytype_enum_old" USING "thisEntityType"::"text"::"edge_thisentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "edge_thisentitytype_enum"')
    await queryRunner.query('ALTER TYPE "edge_thisentitytype_enum_old" RENAME TO  "edge_thisentitytype_enum"')
    await queryRunner.query('CREATE TYPE "edge_entitytype_enum_old" AS ENUM(\'ActionX\', \'Activity\', \'ChatRoom\', \'Comment\', \'CommentReceipt\', \'CompletedAction\', \'DeviceInfo\', \'Edge\', \'Effect\', \'Field\', \'Job\', \'Location\', \'NewsfeedItem\', \'Notification\', \'QEdge\', \'Receipt\', \'Report\', \'SDist\', \'Tile\', \'UnObject\', \'User\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "entityType" DROP DEFAULT')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "entityType" TYPE "edge_entitytype_enum_old" USING "entityType"::"text"::"edge_entitytype_enum_old"')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "entityType" SET DEFAULT \'Edge\'')
    await queryRunner.query('DROP TYPE "edge_entitytype_enum"')
    await queryRunner.query('ALTER TYPE "edge_entitytype_enum_old" RENAME TO  "edge_entitytype_enum"')
    await queryRunner.query('DROP INDEX "IDX_ca683d2297753686447c3a1c51"')
    await queryRunner.query('DROP INDEX "IDX_8ce9fa6de3ccb2f2e1c7faf3b0"')
    await queryRunner.query('DROP TABLE "user_newsfeed_item_edge"')
    await queryRunner.query('DROP TYPE "user_newsfeed_item_edge_entitytype_enum"')
  }

}
