import {MigrationInterface, QueryRunner} from 'typeorm'

export class ChangeItemNames1593627051259 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('UPDATE "action_x" SET "name" = \'artisanal_brioche_bun_8\' WHERE "name" = \'Action.Rewarded.BriocheBun\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'artisanal_brioche_bun_8\' WHERE "actionName" = \'Action.Rewarded.BriocheBun\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'avocado_9\' WHERE "name" = \'Action.Rewarded.Avocado\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'avocado_9\' WHERE "actionName" = \'Action.Rewarded.Avocado\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'avocado_toast_10\' WHERE "name" = \'Action.Rewarded.AvocadoToast\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'avocado_toast_10\' WHERE "actionName" = \'Action.Rewarded.AvocadoToast\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'burner_phone_15\' WHERE "name" = \'Action.Rewarded.BurnerPhone\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'burner_phone_15\' WHERE "actionName" = \'Action.Rewarded.BurnerPhone\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'chatty_boomer_22\' WHERE "name" = \'Action.Rewarded.ChattyBoomer\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'chatty_boomer_22\' WHERE "actionName" = \'Action.Rewarded.ChattyBoomer\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'coachella_dust_23\' WHERE "name" = \'Action.Rewarded.CoachellaDust\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'coachella_dust_23\' WHERE "actionName" = \'Action.Rewarded.CoachellaDust\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'coconut_25\' WHERE "name" = \'Action.Rewarded.Coconut\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'coconut_25\' WHERE "actionName" = \'Action.Rewarded.Coconut\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'face_wash_91\' WHERE "name" = \'Action.Rewarded.FoamingFace\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'face_wash_91\' WHERE "actionName" = \'Action.Rewarded.FoamingFace\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'flour_111\' WHERE "name" = \'Action.Rewarded.Flour\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'flour_111\' WHERE "actionName" = \'Action.Rewarded.Flour\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'hair_mousse_6\' WHERE "name" = \'Action.Rewarded.HairMousse\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'hair_mousse_6\' WHERE "actionName" = \'Action.Rewarded.HairMousse\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'karen_burger_52\' WHERE "name" = \'Action.Rewarded.KarenBurger\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'karen_burger_52\' WHERE "actionName" = \'Action.Rewarded.KarenBurger\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'milky_tea_44\' WHERE "name" = \'Action.Rewarded.MilkyTea\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'milky_tea_44\' WHERE "actionName" = \'Action.Rewarded.MilkyTea\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'natural_south_sea_sponge_62\' WHERE "name" = \'Action.Rewarded.SeaSponge\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'natural_south_sea_sponge_62\' WHERE "actionName" = \'Action.Rewarded.SeaSponge\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'san_francisco_sourdough_bread_85\' WHERE "name" = \'Action.Rewarded.Bread\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'san_francisco_sourdough_bread_85\' WHERE "actionName" = \'Action.Rewarded.Bread\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'savage_boba_tea_86\' WHERE "name" = \'Action.Rewarded.SavageBobaTea\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'savage_boba_tea_86\' WHERE "actionName" = \'Action.Rewarded.SavageBobaTea\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'skin_mask_83\' WHERE "name" = \'Action.Rewarded.SkinMask\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'skin_mask_83\' WHERE "actionName" = \'Action.Rewarded.SkinMask\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'patty_100\' WHERE "name" = \'Action.Rewarded.StinkyPatty\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'patty_100\' WHERE "actionName" = \'Action.Rewarded.StinkyPatty\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'tapioca_pearls_104\' WHERE "name" = \'Action.Rewarded.TapiocaPearls\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'tapioca_pearls_104\' WHERE "actionName" = \'Action.Rewarded.TapiocaPearls\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'tea_leaves_109\' WHERE "name" = \'Action.Rewarded.TeaLeaf\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'tea_leaves_109\' WHERE "actionName" = \'Action.Rewarded.TeaLeaf\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'tiger_milk_110\' WHERE "name" = \'Action.Rewarded.TigerMilk\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'tiger_milk_110\' WHERE "actionName" = \'Action.Rewarded.TigerMilk\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'vegan_smoothie_82\' WHERE "name" = \'Action.Rewarded.VeganSmoothie\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'vegan_smoothie_82\' WHERE "actionName" = \'Action.Rewarded.VeganSmoothie\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'wheat_112\' WHERE "name" = \'Action.Rewarded.Wheat\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'wheat_112\' WHERE "actionName" = \'Action.Rewarded.Wheat\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'rotten_patty_1139\' WHERE "name" = \'Action.Rewarded.StinkyPatty.Expired\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'rotten_patty_1139\' WHERE "actionName" = \'Action.Rewarded.StinkyPatty.Expired\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'spoiled_tiger_milk_1138\' WHERE "name" = \'Action.Rewarded.TigerMilk.Expired\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'spoiled_tiger_milk_1138\' WHERE "actionName" = \'Action.Rewarded.TigerMilk.Expired\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'mosquito_625\' WHERE "name" = \'Action.General.MosquitoBite\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'mosquito_625\' WHERE "actionName" = \'Action.General.MosquitoBite\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'knife_585\' WHERE "name" = \'Action.General.Knife\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'knife_585\' WHERE "actionName" = \'Action.General.Knife\'')
    // Dups
    await queryRunner.query('DELETE FROM "action_x_instance" WHERE "actionName" = \'Action.Rewarded.SanFranciscoSourDough\'')
    await queryRunner.query('DELETE FROM "action_x" WHERE "name" = \'Action.Rewarded.SanFranciscoSourDough\'')
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.BriocheBun\' WHERE "name" = \'artisanal_brioche_bun_8\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.BriocheBun\' WHERE "actionName" = \'artisanal_brioche_bun_8\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.Avocado\' WHERE "name" = \'avocado_9\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.Avocado\' WHERE "actionName" = \'avocado_9\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.AvocadoToast\' WHERE "name" = \'avocado_toast_10\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.AvocadoToast\' WHERE "actionName" = \'avocado_toast_10\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.BurnerPhone\' WHERE "name" = \'burner_phone_15\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.BurnerPhone\' WHERE "actionName" = \'burner_phone_15\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.ChattyBoomer\' WHERE "name" = \'chatty_boomer_22\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.ChattyBoomer\' WHERE "actionName" = \'chatty_boomer_22\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.CoachellaDust\' WHERE "name" = \'coachella_dust_23\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.CoachellaDust\' WHERE "actionName" = \'coachella_dust_23\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.Coconut\' WHERE "name" = \'coconut_25\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.Coconut\' WHERE "actionName" = \'coconut_25\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.FoamingFace\' WHERE "name" = \'face_wash_91\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.FoamingFace\' WHERE "actionName" = \'face_wash_91\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.Flour\' WHERE "name" = \'flour_111\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.Flour\' WHERE "actionName" = \'flour_111\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.HairMousse\' WHERE "name" = \'hair_mousse_6\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.HairMousse\' WHERE "actionName" = \'hair_mousse_6\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.KarenBurger\' WHERE "name" = \'karen_burger_52\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.KarenBurger\' WHERE "actionName" = \'karen_burger_52\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.MilkyTea\' WHERE "name" = \'milky_tea_44\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.MilkyTea\' WHERE "actionName" = \'milky_tea_44\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.SeaSponge\' WHERE "name" = \'natural_south_sea_sponge_62\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.SeaSponge\' WHERE "actionName" = \'natural_south_sea_sponge_62\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.Bread\' WHERE "name" = \'san_francisco_sourdough_bread_85\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.Bread\' WHERE "actionName" = \'san_francisco_sourdough_bread_85\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.SavageBobaTea\' WHERE "name" = \'savage_boba_tea_86\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.SavageBobaTea\' WHERE "actionName" = \'savage_boba_tea_86\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.SkinMask\' WHERE "name" = \'skin_mask_83\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.SkinMask\' WHERE "actionName" = \'skin_mask_83\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.StinkyPatty\' WHERE "name" = \'patty_100\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.StinkyPatty\' WHERE "actionName" = \'patty_100\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.TapiocaPearls\' WHERE "name" = \'tapioca_pearls_104\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.TapiocaPearls\' WHERE "actionName" = \'tapioca_pearls_104\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.TeaLeaf\' WHERE "name" = \'tea_leaves_109\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.TeaLeaf\' WHERE "actionName" = \'tea_leaves_109\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.TigerMilk\' WHERE "name" = \'tiger_milk_110\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.TigerMilk\' WHERE "actionName" = \'tiger_milk_110\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.VeganSmoothie\' WHERE "name" = \'vegan_smoothie_82\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.VeganSmoothie\' WHERE "actionName" = \'vegan_smoothie_82\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.Wheat\' WHERE "name" = \'wheat_112\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.Wheat\' WHERE "actionName" = \'wheat_112\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.StinkyPatty.Expired\' WHERE "name" = \'rotten_patty_1139\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.StinkyPatty.Expired\' WHERE "actionName" = \'rotten_patty_1139\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.Rewarded.TigerMilk.Expired\' WHERE "name" = \'spoiled_tiger_milk_1138\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.Rewarded.TigerMilk.Expired\' WHERE "actionName" = \'spoiled_tiger_milk_1138\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.General.MosquitoBite\' WHERE "name" = \'mosquito_625\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.General.MosquitoBite\' WHERE "actionName" = \'mosquito_625\'')
    await queryRunner.query('UPDATE "action_x" SET "name" = \'Action.General.Knife\' WHERE "name" = \'knife_585\'')
    await queryRunner.query('UPDATE "action_x_instance" SET "actionName" = \'Action.General.Knife\' WHERE "actionName" = \'knife_585\'')
  }

}
